dcConsData = [
	{name:"BB돌없찐.gif",			keywords:["BB연차각", "BB연챠각"],	tags:["페그오", "BB", "BB콘"]},
	{name:"가레스헤.png",			keywords:["가레스헤"],	tags:["페그오", "가레스"]},
	{name:"알테레기.gif",			keywords:["알테레기"],	tags:["페그오", "알테라", "리요"]},
	{name:"알테흔들.gif",			keywords:["알테흔들"],	tags:["페그오", "알테라", "리요"]},
	{name:"구다흥분.gif",			keywords:["구다흥분"],	tags:["페그오", "구다코", "리요"]},
	{name:"포우로딩.gif",			keywords:["포우로딩"],	tags:["페그오", "포우", "리요"]},
	{name:"고흐룰루.png",			keywords:["고흐룰루"],	tags:["페그오", "고흐", "포리너콘"]},
	{name:"그레커엽.gif",			keywords:["그레커엽"],	tags:["페그오", "그레이", "사건부"]},
	{name:"그오섭종.png",			keywords:["그오섭종"],	tags:["페그오", "모르건"]},
	{name:"네로짝.png",			keywords:["네로짝"],	tags:["페그오", "네로"]},
	{name:"바반시싫.png",			keywords:["바반시싫"],	tags:["페그오", "바반시"]},
	{name:"바반시좋.png",			keywords:["바반시좋"],	tags:["페그오", "바반시"]},
	{name:"버탈님아.png",			keywords:["버탈님아"],	tags:["페그오", "아탈란테"]},
	{name:"아탈신.png",			keywords:["아탈신"],	tags:["페그오", "아탈란테"]},
	{name:"오베페페.png",			keywords:["오베페페"],	tags:["페그오", "오베론"]},
	{name:"요슬놀람.png",			keywords:["요슬놀람"],	tags:["페그오", "멜루진", "요슬롯"]},
	{name:"요슬맡겨.png",			keywords:["요슬맡겨"],	tags:["페그오", "멜루진", "요슬롯"]},
	{name:"요슬최강.png",			keywords:["요슬최강"],	tags:["페그오", "멜루진", "요슬롯"]},
	{name:"지지뜬1.png",			keywords:["지지뜬1"],	tags:["페그오", "가챠"]},
	{name:"지지뜬2.png",			keywords:["지지뜬2"],	tags:["페그오", "가챠"]},
	{name:"이걸믿네.png",			keywords:["이걸믿네"],	tags:["페그오", "가챠"]},
	{name:"자신있나.png",			keywords:["자신있나"],	tags:["페그오", "가챠"]},
	{name:"자폭ㄱ.png",			keywords:["자폭ㄱ"],	tags:["페그오", "진궁"]},
	{name:"지존전사.png",			keywords:["지존전사"],	tags:["페그오", "아슈바타만"]},
	{name:"청밥밥상.gif",			keywords:["청밥밥상"],	tags:["페그오", "청밥", "에미야밥상"]},
	{name:"청밥흐물.gif",			keywords:["청밥흐물"],	tags:["페그오", "청밥", "에미야밥상"]},
	{name:"캐밥없찐.png",			keywords:["캐밥없찐"],	tags:["페그오", "캐밥"]},
	{name:"캐밥ㅠㅠ.png",			keywords:["캐밥흑흑"],	tags:["페그오", "캐밥"]},
	{name:"화났니.png",			keywords:["화났니"],	tags:["페그오", "타마모"]},
	{name:"황녀요정.png",			keywords:["황녀요정", "황녀띠밤"],	tags:["페그오", "아나스타샤"]},
	{name:"흔들어라.gif",			keywords:["흔들어라"],	tags:["페그오", "이리야"]},
	{name:"히토미컷.png",			keywords:["히토미컷"],	tags:["페그오", "린"]},
	{name:"1만.png",	keywords:["1만"],	tags:["마작", "작혼", "만수"]},
	{name:"2만.png",	keywords:["2만"],	tags:["마작", "작혼", "만수"]},
	{name:"3만.png",	keywords:["3만"],	tags:["마작", "작혼", "만수"]},
	{name:"4만.png",	keywords:["4만"],	tags:["마작", "작혼", "만수"]},
	{name:"5만.png",	keywords:["5만"],	tags:["마작", "작혼", "만수"]},
	{name:"6만.png",	keywords:["6만"],	tags:["마작", "작혼", "만수"]},
	{name:"7만.png",	keywords:["7만"],	tags:["마작", "작혼", "만수"]},
	{name:"8만.png",	keywords:["8만"],	tags:["마작", "작혼", "만수"]},
	{name:"9만.png",	keywords:["9만"],	tags:["마작", "작혼", "만수"]},
	{name:"5만도라.png",	keywords:["5만도라"],	tags:["마작", "작혼", "만수"]},
	{name:"1통.png",	keywords:["1통","1핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"2통.png",	keywords:["2통","2핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"3통.png",	keywords:["3통","3핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"4통.png",	keywords:["4통","4핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"5통.png",	keywords:["5통","5핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"6통.png",	keywords:["6통","6핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"7통.png",	keywords:["7통","7핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"8통.png",	keywords:["8통","8핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"9통.png",	keywords:["9통","9핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"5통도라.png",	keywords:["5통도라","5핀도라"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"1삭.png",	keywords:["1삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"2삭.png",	keywords:["2삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"3삭.png",	keywords:["3삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"4삭.png",	keywords:["4삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"5삭.png",	keywords:["5삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"6삭.png",	keywords:["6삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"7삭.png",	keywords:["7삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"8삭.png",	keywords:["8삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"9삭.png",	keywords:["9삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"5삭도라.png",	keywords:["5삭도라"],	tags:["마작", "작혼", "삭수"]},
	{name:"백.png",	keywords:["백"],	tags:["마작", "작혼"]},
	{name:"발.png",	keywords:["발"],	tags:["마작", "작혼"]},
	{name:"중.png",	keywords:["중"],	tags:["마작", "작혼"]},
	{name:"동.png",	keywords:["동"],	tags:["마작", "작혼"]},
	{name:"남.png",	keywords:["남"],	tags:["마작", "작혼"]},
	{name:"서.png",	keywords:["서"],	tags:["마작", "작혼"]},
	{name:"북.png",	keywords:["북"],	tags:["마작", "작혼"]},
	{name:"치.png",	keywords:["치"],	tags:["마작", "작혼"]},
	{name:"깡.png",	keywords:["깡", "캉"],	tags:["마작", "작혼"]},
	{name:"퐁.png",	keywords:["퐁", "뻥", "펑"],	tags:["마작", "작혼"]},
	{name:"론.png",	keywords:["론"],	tags:["마작", "작혼"]},
	{name:"쯔모.png",	keywords:["쯔모"],	tags:["마작", "작혼"]},
	{name:"리치.png",	keywords:["리치"],	tags:["마작", "작혼"]},
	{name:"스킵.png",	keywords:["스킵"],	tags:["마작", "작혼"]},
	{name:"유국.png",	keywords:["유국"],	tags:["마작", "작혼"]}


];