dcConsData = [
	{name:"고흐룰루.png",	keywords:["고흐룰루", "왈랄랄루"],	tags:["고흐", "페그오"]},
	{name:"고흐의문.png",	keywords:["고흐의문"],	tags:["고흐", "페그오"]},
	{name:"고흐무섭.png",	keywords:["고흐무섭"],	tags:["고흐", "페그오"]},
	{name:"1만.png",	keywords:["1만"],	tags:["마작", "작혼", "만수"]},
	{name:"2만.png",	keywords:["2만"],	tags:["마작", "작혼", "만수"]},
	{name:"3만.png",	keywords:["3만"],	tags:["마작", "작혼", "만수"]},
	{name:"4만.png",	keywords:["4만"],	tags:["마작", "작혼", "만수"]},
	{name:"5만.png",	keywords:["5만"],	tags:["마작", "작혼", "만수"]},
	{name:"6만.png",	keywords:["6만"],	tags:["마작", "작혼", "만수"]},
	{name:"7만.png",	keywords:["7만"],	tags:["마작", "작혼", "만수"]},
	{name:"8만.png",	keywords:["8만"],	tags:["마작", "작혼", "만수"]},
	{name:"9만.png",	keywords:["9만"],	tags:["마작", "작혼", "만수"]},
	{name:"5만도라.png",	keywords:["5만도라"],	tags:["마작", "작혼", "만수"]},
	{name:"1통.png",	keywords:["1통","1핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"2통.png",	keywords:["2통","2핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"3통.png",	keywords:["3통","3핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"4통.png",	keywords:["4통","4핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"5통.png",	keywords:["5통","5핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"6통.png",	keywords:["6통","6핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"7통.png",	keywords:["7통","7핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"8통.png",	keywords:["8통","8핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"9통.png",	keywords:["9통","9핀"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"5통도라.png",	keywords:["5통도라","5핀도라"],	tags:["마작", "작혼", "통수","핀수"]},
	{name:"1삭.png",	keywords:["1삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"2삭.png",	keywords:["2삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"3삭.png",	keywords:["3삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"4삭.png",	keywords:["4삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"5삭.png",	keywords:["5삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"6삭.png",	keywords:["6삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"7삭.png",	keywords:["7삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"8삭.png",	keywords:["8삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"9삭.png",	keywords:["9삭"],	tags:["마작", "작혼", "삭수"]},
	{name:"5삭도라.png",	keywords:["5삭도라"],	tags:["마작", "작혼", "삭수"]},
	{name:"백.png",	keywords:["백"],	tags:["마작", "작혼"]},
	{name:"발.png",	keywords:["발"],	tags:["마작", "작혼"]},
	{name:"중.png",	keywords:["중"],	tags:["마작", "작혼"]},
	{name:"동.png",	keywords:["동"],	tags:["마작", "작혼"]},
	{name:"남.png",	keywords:["남"],	tags:["마작", "작혼"]},
	{name:"서.png",	keywords:["서"],	tags:["마작", "작혼"]},
	{name:"북.png",	keywords:["북"],	tags:["마작", "작혼"]},
	{name:"치.png",	keywords:["치"],	tags:["마작", "작혼"]},
	{name:"깡.png",	keywords:["깡", "캉"],	tags:["마작", "작혼"]},
	{name:"퐁.png",	keywords:["퐁", "뻥", "펑"],	tags:["마작", "작혼"]},
	{name:"론.png",	keywords:["론"],	tags:["마작", "작혼"]},
	{name:"쯔모.png",	keywords:["쯔모"],	tags:["마작", "작혼"]},
	{name:"리치.png",	keywords:["리치"],	tags:["마작", "작혼"]},
	{name:"스킵.png",	keywords:["스킵"],	tags:["마작", "작혼"]},
	{name:"유국.png",	keywords:["유국"],	tags:["마작", "작혼"]},
	{name:"짱냥놀람.png",	keywords:["짱냥놀람"],	tags:["마작", "작혼", "짱냥", "이치히메"]},
	{name:"짱냥따봉.png",	keywords:["짱냥따봉"],	tags:["마작", "작혼", "짱냥", "이치히메"]},
	{name:"짱냥버럭.png",	keywords:["짱냥버럭"],	tags:["마작", "작혼", "짱냥", "이치히메"]},
	{name:"짱냥부들.png",	keywords:["짱냥부들"],	tags:["마작", "작혼", "짱냥", "이치히메"]},
	{name:"짱냥빡침.png",	keywords:["짱냥빡침"],	tags:["마작", "작혼", "짱냥", "이치히메"]},
	{name:"짱냥심각.png",	keywords:["짱냥심각"],	tags:["마작", "작혼", "짱냥", "이치히메"]},
	{name:"짱냥음료.png",	keywords:["짱냥음료"],	tags:["마작", "작혼", "짱냥", "이치히메"]},
	{name:"짱냥음식.png",	keywords:["짱냥음식"],	tags:["마작", "작혼", "짱냥", "이치히메"]},
	{name:"짱냥집중.png",	keywords:["짱냥집중"],	tags:["마작", "작혼", "짱냥", "이치히메"]},
	{name:"짱냥하트.png",	keywords:["짱냥하트"],	tags:["마작", "작혼", "짱냥", "이치히메"]},
	{name:"짱냥한심.png",	keywords:["짱냥한심"],	tags:["마작", "작혼", "짱냥", "이치히메"]},
	{name:"짱냥화남.png",	keywords:["짱냥화남"],	tags:["마작", "작혼", "짱냥", "이치히메"]},
	{name:"미키빡침.png",	keywords:["미키빡침"],	tags:["마작", "작혼", "니카이도 미키"]},
	{name:"미키뿜음.png",	keywords:["미키뿜음"],	tags:["마작", "작혼", "니카이도 미키"]},
	{name:"미키눈물.png",	keywords:["미키눈물"],	tags:["마작", "작혼", "니카이도 미키"]},
	{name:"미키대박.png",	keywords:["미키대박"],	tags:["마작", "작혼", "니카이도 미키"]},
	{name:"미키범죄.png",	keywords:["미키범죄"],	tags:["마작", "작혼", "니카이도 미키"]},
	{name:"미키섹시.png",	keywords:["미키섹시"],	tags:["마작", "작혼", "니카이도 미키"]},
	{name:"미키애교.png",	keywords:["미키애교"],	tags:["마작", "작혼", "니카이도 미키"]},
	{name:"미키음료.png",	keywords:["미키음료"],	tags:["마작", "작혼", "니카이도 미키"]},
	{name:"미키하트.png",	keywords:["미키하트"],	tags:["마작", "작혼", "니카이도 미키"]},
	{name:"미키한심.png",	keywords:["미키한심"],	tags:["마작", "작혼", "니카이도 미키"]},
	{name:"미키흠칫.png",	keywords:["미키흠칫"],	tags:["마작", "작혼", "니카이도 미키"]},
	{name:"미키얀데레.png",	keywords:["미키얀데레"],	tags:["마작", "작혼", "니카이도 미키"]},
	{name:"핵아닌데.gif",	keywords:["핵아닌데"],	tags:["우리핵"]},
	{name:"핵박수.gif",	keywords:["핵박수"],	tags:["우리핵"]},
	{name:"핵박수2.gif",	keywords:["핵박수2"],	tags:["우리핵"]},
	{name:"핵인사.gif",	keywords:["핵인사"],	tags:["우리핵"]},
	{name:"냥따봉2.gif",	keywords:["짱냥따봉2"],	tags:["마작", "작혼", "짱냥", "이치히메"]},
	{name:"냥슬픔.gif",	keywords:["냥슬픔"],	tags:["냥콘"]},
	{name:"냥슬픔2.gif",	keywords:["냥슬픔2"],	tags:["냥콘"]},
	{name:"냥읍.gif",	keywords:["냥읍"],	tags:["냥콘"]},
	{name:"제리감사.gif",	keywords:["제리감사"],	tags:["제리콘"]},
	{name:"제리냠냠.gif",	keywords:["제리냠냠"],	tags:["제리콘"]},
	{name:"제리미침.gif",	keywords:["제리미침"],	tags:["제리콘"]},
	{name:"제리줘팸.gif",	keywords:["제리줘팸"],	tags:["제리콘"]},
	{name:"제리폭소.gif",	keywords:["제리폭소"],	tags:["제리콘"]},
	{name:"가소롭다.png",	keywords:["가소롭"],	tags:["달걀콘"]},
	{name:"가즈아.png",	keywords:["가즈아"],	tags:["달걀콘"]},
	{name:"깨닫다.png",	keywords:["깨닫"],	tags:["달걀콘"]},
	{name:"끄덕끄덕.png",	keywords:["끄덕"],	tags:["달걀콘"]},
	{name:"놀랍다.png",	keywords:["놀랍"],	tags:["달걀콘"]},
	{name:"두렵다.png",	keywords:["두렵"],	tags:["달걀콘"]},
	{name:"띠껍다.png",	keywords:["띠껍"],	tags:["달걀콘"]},
	{name:"마참내.png",	keywords:["마참내"],	tags:["달걀콘"]},
	{name:"슬프다.png",	keywords:["슬프다"],	tags:["달걀콘"]},
	{name:"시간절약.png",	keywords:["시간절약"],	tags:["달걀콘"]},
	{name:"실망하다.png",	keywords:["실망"],	tags:["달걀콘"]},
	{name:"이상하다.png",	keywords:["이상"],	tags:["달걀콘"]},
	{name:"절레절레.png",	keywords:["절레"],	tags:["달걀콘"]},
	{name:"졸리다.png",	keywords:["졸리다"],	tags:["달걀콘"]},
	{name:"죄송하다.png",	keywords:["죄송하다"],	tags:["달걀콘"]},
	{name:"즐겁다.png",	keywords:["즐겁"],	tags:["달걀콘"]},
	{name:"혐오한다.png",	keywords:["혐오"],	tags:["달걀콘"]},
	{name:"화난다.png",	keywords:["화"],	tags:["달걀콘"]},
	{name:"흥미롭다.png",	keywords:["흥미롭"],	tags:["달걀콘"]},
	{name:"ㅗㅜㅑ.png",	keywords:["ㅗㅜㅑ"],	tags:["달걀콘"]},
	{name:"붕쯔붕쯔.gif",	keywords:["붕쯔붕쯔"],	tags:["참피"]},
	{name:"와바랏.png",	keywords:["와바랏", "와봐랏"],	tags:["참피"]},
	{name:"쿠이쿠이.png",	keywords:["쿠이쿠이"],	tags:["참피"]},
	{name:"슈메1.png",	keywords:["슈메1"],	tags:["슈퍼메롱콘"]},
	{name:"슈메2.png",	keywords:["슈메2"],	tags:["슈퍼메롱콘"]},
	{name:"슈메3.png",	keywords:["슈메3"],	tags:["슈퍼메롱콘"]},
	{name:"슈메4.png",	keywords:["슈메깡", "슈메4"],	tags:["슈퍼메롱콘"]},
	{name:"슈메5.png",	keywords:["슈메5"],	tags:["슈퍼메롱콘"]},
	{name:"슈메6.png",	keywords:["슈메6"],	tags:["슈퍼메롱콘"]},
	{name:"슈메7.png",	keywords:["슈메한심", "슈메7"],	tags:["슈퍼메롱콘"]},
	{name:"슈메8.png",	keywords:["슈메8"],	tags:["슈퍼메롱콘"]},
	{name:"슈메9.png",	keywords:["슈메엄준식", "슈메9"],	tags:["슈퍼메롱콘"]},
	{name:"슈메10.png",	keywords:["슈메10"],	tags:["슈퍼메롱콘"]},
	{name:"슈메11.png",	keywords:["슈메11"],	tags:["슈퍼메롱콘"]},
	{name:"슈메12.png",	keywords:["슈메12"],	tags:["슈퍼메롱콘"]},
	{name:"슈메13.png",	keywords:["슈메13"],	tags:["슈퍼메롱콘"]},
	{name:"슈메14.png",	keywords:["슈메14"],	tags:["슈퍼메롱콘"]},
	{name:"슈메15.png",	keywords:["슈메15"],	tags:["슈퍼메롱콘"]},
	{name:"슈메16.gif",	keywords:["슈메16"],	tags:["슈퍼메롱콘"]},
	{name:"슈메17.gif",	keywords:["슈메17"],	tags:["슈퍼메롱콘"]},
	{name:"슈메18.gif",	keywords:["슈메18"],	tags:["슈퍼메롱콘"]},
	{name:"슈메19.gif",	keywords:["슈메19"],	tags:["슈퍼메롱콘"]},
	{name:"슈메20.gif",	keywords:["슈메20"],	tags:["슈퍼메롱콘"]},
	{name:"슈메21.gif",	keywords:["슈메21"],	tags:["슈퍼메롱콘"]},
	{name:"슈메22.gif",	keywords:["슈메22"],	tags:["슈퍼메롱콘"]},
	{name:"슈메23.gif",	keywords:["슈메23"],	tags:["슈퍼메롱콘"]},
	{name:"슈메24.gif",	keywords:["슈메24"],	tags:["슈퍼메롱콘"]},
	{name:"슈메25.gif",	keywords:["슈메25"],	tags:["슈퍼메롱콘"]},
	{name:"도지.gif",	keywords:["도지"],	tags:["도지"]},
	{name:"칠레감탄1.gif",	keywords:["칠레1"],	tags:["칠레콘"]},
	{name:"칠레감탄2.gif",	keywords:["칠레2"],	tags:["칠레콘"]},
	{name:"칠레감탄3.gif",	keywords:["칠레3"],	tags:["칠레콘"]},
	{name:"칠레감탄4.gif",	keywords:["칠레4"],	tags:["칠레콘"]},
	{name:"칠레감탄5.png",	keywords:["칠레5"],	tags:["칠레콘"]},
	{name:"칠레감탄6.gif",	keywords:["칠레6"],	tags:["칠레콘"]},
	{name:"폰지썩소.gif",	keywords:["폰지썩소"],	tags:[""]},
	{name:"마치.png",	keywords:["마치"],	tags:["검투사"]},
	{name:"번뜩.png",	keywords:["번뜩"],	tags:["검투사"]},

];
